version: 0.0.0.{build}

platform: Any CPU
configuration: Release

skip_tags: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  
before_build:
  - nuget restore "./src/Egor92.CollectionExtensions.sln"

build:
  project: src\Egor92.CollectionExtensions.sln
  publish_nuget: true
  
test:
  assemblies:
    - '**\*.Tests.dll'

artifacts:  
  - path: /.*\.nupkg/
    name: NuGet package
  
deploy:
  # Deploying to NuGet feed
  - provider: NuGet
    api_key:
      secure: Enbbe1MRpwxTk+l70bA1DfoJq62BO4S01RRKFDL4Fx83I/f3W4D4MQJTRXrNwkFj
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      branch: master
  
  # Deploy to GitHub Releases
  - provider: GitHub
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    auth_token:
      secure: F00nbLt278uSgQKKvDMLxc6AXtaZNE4b9WcDfDZ79T1gN23xhpLtoeguU6B0tSuV
    on:
      branch: master
    appveyor_repo_tag: true